// Data awal (seed) — bisa diubah sepenuhnya lewat halaman Kelola Produk.
// Struktur ini dinamis: kategori, produk, dan grup varian bebas ditambah
// sehingga sistem bisa dipakai untuk jenis UMKM apa pun.

export const seedCategories = [
  { id: "cat-makanan", name: "Makanan", icon: "🍲" },
  { id: "cat-snack", name: "Snack", icon: "🍘" },
  { id: "cat-minuman", name: "Minuman", icon: "☕" },
];

export const seedProducts = [
  {
    id: "p-soto-ayam",
    name: "Soto Ayam",
    categoryId: "cat-makanan",
    basePrice: 12000,
    emoji: "🍜",
    stock: 30,
    trackStock: true,
    allowNotes: true,
    notesHint: "Contoh: tanpa daun bawang, tanpa jeruk nipis",
    variantGroups: [
      {
        id: "vg-soto-nasi",
        name: "Nasi",
        type: "single",
        required: true,
        options: [
          { id: "vo-pakai-nasi", name: "Pakai Nasi", priceDelta: 3000 },
          { id: "vo-tanpa-nasi", name: "Tanpa Nasi", priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: "p-soto-daging",
    name: "Soto Daging",
    categoryId: "cat-makanan",
    basePrice: 15000,
    emoji: "🍛",
    stock: 20,
    trackStock: true,
    allowNotes: true,
    notesHint: "Contoh: tanpa daun bawang, kuah dipisah",
    variantGroups: [
      {
        id: "vg-sodag-nasi",
        name: "Nasi",
        type: "single",
        required: true,
        options: [
          { id: "vo-sodag-pakai", name: "Pakai Nasi", priceDelta: 3000 },
          { id: "vo-sodag-tanpa", name: "Tanpa Nasi", priceDelta: 0 },
        ],
      },
    ],
  },
  {
    id: "p-kerupuk",
    name: "Kerupuk",
    categoryId: "cat-snack",
    basePrice: 5000,
    emoji: "🍘",
    stock: 50,
    trackStock: true,
    allowNotes: false,
    variantGroups: [
      {
        id: "vg-kerupuk-rasa",
        name: "Rasa",
        type: "single",
        required: true,
        options: [
          { id: "vo-krp-original", name: "Original", priceDelta: 0 },
          { id: "vo-krp-pedas", name: "Pedas", priceDelta: 500 },
        ],
      },
    ],
  },
  {
    id: "p-peyek",
    name: "Peyek",
    categoryId: "cat-snack",
    basePrice: 15000,
    emoji: "🥜",
    stock: 40,
    trackStock: true,
    allowNotes: false,
    variantGroups: [
      {
        id: "vg-peyek-jenis",
        name: "Jenis",
        type: "single",
        required: true,
        options: [
          { id: "vo-pyk-kacang", name: "Kacang", priceDelta: 0 },
          { id: "vo-pyk-teri", name: "Teri", priceDelta: 3000 },
          { id: "vo-pyk-kedelai", name: "Kedelai", priceDelta: 0 },
          { id: "vo-pyk-campur", name: "Campur", priceDelta: 2000 },
        ],
      },
      {
        id: "vg-peyek-berat",
        name: "Berat",
        type: "single",
        required: true,
        options: [
          { id: "vo-pyk-14", name: "1/4 kg", priceDelta: 0 },
          { id: "vo-pyk-12", name: "1/2 kg", priceDelta: 13000 },
          { id: "vo-pyk-1", name: "1 kg", priceDelta: 38000 },
        ],
      },
    ],
  },
  {
    id: "p-kopi-hitam",
    name: "Kopi Hitam",
    categoryId: "cat-minuman",
    basePrice: 6000,
    emoji: "☕",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    notesHint: "Contoh: gula sedikit, tanpa gula",
    variantGroups: [
      {
        id: "vg-kopi-saji",
        name: "Penyajian",
        type: "single",
        required: true,
        options: [
          { id: "vo-kopi-panas", name: "Panas", priceDelta: 0 },
          { id: "vo-kopi-es", name: "Es", priceDelta: 1000 },
        ],
      },
    ],
  },
  {
    id: "p-kopi-sachet",
    name: "Kopi Sachet",
    categoryId: "cat-minuman",
    basePrice: 4000,
    emoji: "🥤",
    stock: 80,
    trackStock: true,
    allowNotes: false,
    variantGroups: [],
  },
  {
    id: "p-teh-manis-hangat",
    name: "Teh Manis Hangat",
    categoryId: "cat-minuman",
    basePrice: 3500,
    emoji: "🍵",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    notesHint: "Contoh: gula sedikit",
    variantGroups: [],
  },
  {
    id: "p-es-teh-manis",
    name: "Es Teh Manis",
    categoryId: "cat-minuman",
    basePrice: 4000,
    emoji: "🧋",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    notesHint: "Contoh: es sedikit, gula sedikit",
    variantGroups: [],
  },
  {
    id: "p-es-jeruk",
    name: "Es Jeruk",
    categoryId: "cat-minuman",
    basePrice: 5000,
    emoji: "🍊",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    notesHint: "Contoh: es sedikit",
    variantGroups: [],
  },
  {
    id: "p-jeruk-panas",
    name: "Jeruk Panas",
    categoryId: "cat-minuman",
    basePrice: 5000,
    emoji: "🍹",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    variantGroups: [],
  },
  {
    id: "p-wedang-jahe",
    name: "Wedang Jahe",
    categoryId: "cat-minuman",
    basePrice: 6000,
    emoji: "🫖",
    stock: 100,
    trackStock: false,
    allowNotes: true,
    variantGroups: [],
  },
];

export const seedSettings = {
  storeName: "Kafe Ama",
  storeAddress: "Jl. Contoh No. 1",
  storePhone: "0812-0000-0000",
  taxPercent: 0,
  receiptFooter: "Terima kasih sudah berbelanja 🙏",
};
